name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install poetry
        run: python -m pip install poetry
      - name: Setup TestPyPI repository
        run: |
             poetry config repositories.pypi https://upload.pypi.org/legacy/
             poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish package
        run: poetry publish --build -r pypi