name: Publish to Test PyPI
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install poetry
        run: python -m pip install poetry
      - name: Setup TestPyPI repository
        run: |
             poetry config repositories.testpypi https://test.pypi.org/legacy/
             poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}
      - name: Publish package
        run: poetry publish --build -r testpypi